version: '3'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: your_existing_database_name
      MYSQL_USER: your_existing_username
      MYSQL_PASSWORD: your_existing_password
    volumes:
      - ./database:/var/lib/mysql